name: biinge
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=biinge
      - APP_ADDRESS=0.0.0.0:8080
      - CLIENT_URL=http://localhost:3000
      - DATABASE_DSN=postgres://postgres:postgres@database:5432/biinge-development?sslmode=disable
      - LOG_LEVEL=info
    networks:
      - biinge-network

  database:
    image: postgres:16.4-alpine
    volumes:
      - biinge-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
    networks:
      - biinge-network

networks:
  biinge-network:
    name: biinge-network
    external: true

volumes:
  biinge-database:
