// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/accounts.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/accounts.go -destination=internal/app/controllers/accounts_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountsController is a mock of AccountsController interface.
type MockAccountsController struct {
	ctrl     *gomock.Controller
	recorder *MockAccountsControllerMockRecorder
	isgomock struct{}
}

// MockAccountsControllerMockRecorder is the mock recorder for MockAccountsController.
type MockAccountsControllerMockRecorder struct {
	mock *MockAccountsController
}

// NewMockAccountsController creates a new mock instance.
func NewMockAccountsController(ctrl *gomock.Controller) *MockAccountsController {
	mock := &MockAccountsController{ctrl: ctrl}
	mock.recorder = &MockAccountsControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountsController) EXPECT() *MockAccountsControllerMockRecorder {
	return m.recorder
}

// HandleUpdate mocks base method.
func (m *MockAccountsController) HandleUpdate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUpdate", w, r)
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockAccountsControllerMockRecorder) HandleUpdate(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockAccountsController)(nil).HandleUpdate), w, r)
}

// Me mocks base method.
func (m *MockAccountsController) Me(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Me", w, r)
}

// Me indicates an expected call of Me.
func (mr *MockAccountsControllerMockRecorder) Me(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAccountsController)(nil).Me), w, r)
}
